export type IntentStatus = 'ALIVE' | 'SATISFIED' | 'REVOKED';
export type IntentTerminality = 'DISCRETE' | 'CONTINUOUS' | 'TERMINAL';

export interface Intent {
  id: string;
  description: string;
  status: IntentStatus;
  terminality: IntentTerminality;
  createdAt: number;
  lastProposalAt?: number;
  proposalCooldownUntil?: number;
}

export type GoalProposalStatus = 'PENDING_REVIEW' | 'APPROVED' | 'REJECTED' | 'EXPIRED' | 'SUPERSEDED';

export type CandidateCategory = 'ALIGNED' | 'OBJECTIVE' | 'EXPLORATORY';

export interface CandidateEvaluationVector {
  intentAlignment: number;
  outcomeQuality: number;
  acceptanceProbability: number;
  historicalOutcomeEffectiveness: number;
  diversityContribution: number;
}

export type CandidatePlanStepKind = 'OBSERVE' | 'ANALYZE' | 'COMPARE' | 'PROPOSE';

export interface CandidatePlanStep {
  id: string;
  kind: CandidatePlanStepKind;
  title: string;
  dependsOn: string[];
}

export interface CandidateStrategy {
  objective: string;
  assumptions: string[];
  risks: string[];
  steps: CandidatePlanStep[];
  requiredCapabilities: string[];
  requiresHumanApproval: true;
  worldStateDomains: string[];
}

export interface SwarmReview {
  runId: string;
  status: 'COMPLETED' | 'PARTIAL';
  taskStatuses: Array<{ taskId: string; role: string; status: string; errorMessage?: string }>;
  completedAt: number;
  requiresHumanApproval: true;
}

export interface GoalCandidate {
  id: string;
  category: CandidateCategory;
  title: string;
  rationale: string;
  evaluationVector?: CandidateEvaluationVector;
  strategy: CandidateStrategy;
  /** Optional advisory review generated by the proposal-only swarm. */
  swarmReview?: SwarmReview;
  strategyMetadata?: Record<string, any>;
}

export interface GoalProposal {
  id: string;
  parentIntentId: string;
  candidates: GoalCandidate[];
  status: GoalProposalStatus;
  createdAt: number;
  selectedCandidateId?: string;
}

export interface RepresentationGap {
  intentId: string;
  reason: 'NO_ACTIVE_REPRESENTATION';
  detectedAt: number;
}

export interface IntentCoverage {
  intentId: string;
  activeGoals: number;
  blockedGoals: number;
  dormantGoals: number;
  represented: boolean;
}

export interface RepresentationAuditReport {
  timestamp: number;
  coverage: IntentCoverage[];
  gaps: RepresentationGap[];
}
