export enum MemorySource {
  SYSTEM_EVENT = 'SYSTEM_EVENT',
  USER_STATEMENT = 'USER_STATEMENT',
  USER_DIRECT_INSTRUCTION = 'USER_DIRECT_INSTRUCTION',
  BLOCKCHAIN_OBSERVATION = 'BLOCKCHAIN_OBSERVATION',
  REFLECTION_INFERENCE = 'REFLECTION_INFERENCE',
  EXTERNAL_API = 'EXTERNAL_API'
}
