export enum MemorySource {
  USER_STATEMENT = 'USER_STATEMENT',
  BLOCKCHAIN_OBSERVATION = 'BLOCKCHAIN_OBSERVATION',
  REFLECTION_INFERENCE = 'REFLECTION_INFERENCE',
  EXTERNAL_API = 'EXTERNAL_API'
}
